device_get_capabilities = "unverified"
device_get_device_information_authed = "unverified"
device_get_device_information_bad_auth = "unverified"
device_get_device_information_missing_auth = "unverified"
device_get_hostname = "unverified"
device_get_network_interfaces = "unverified"
device_get_scopes = "unverified"
device_get_services = "unverified"
device_get_system_date_and_time = "unverified"
discovery_probe_match = "unverified"
events_get_event_properties = "unverified"
"events_pull_messages.step0" = "unverified"
"events_pull_messages.step1" = "unverified"
events_unknown_subscription = "unverified"
imaging_get_imaging_settings = "unverified"
media_get_profiles = "unverified"
media_get_snapshot_uri = "unverified"
media_get_stream_uri = "unverified"
media_get_video_encoder_configurations = "unverified"
media_get_video_source_configurations = "unverified"
media_get_video_sources = "unverified"
ptz_absolute_move = "unverified"
ptz_absolute_move_malformed_coord = "unverified"
ptz_continuous_move = "unverified"
ptz_get_configuration_options = "unverified"
ptz_get_configurations = "unverified"
ptz_get_nodes = "unverified"
ptz_get_status = "unverified"
ptz_relative_move = "unverified"
ptz_stop = "unverified"
