device_get_capabilities = "verified"
device_get_device_information_authed = "verified"
device_get_device_information_bad_auth = "verified"
device_get_device_information_missing_auth = "verified"
device_get_hostname = "verified"
device_get_network_interfaces = "verified"
device_get_scopes = "verified"
device_get_services = "verified"
device_get_system_date_and_time = "verified"
discovery_probe_match = "unverified"
events_get_event_properties = "verified"
"events_pull_messages.step0" = "unverified"
"events_pull_messages.step1" = "unverified"
events_unknown_subscription = "verified"
imaging_get_imaging_settings = "verified"
media_get_profiles = "verified"
media_get_snapshot_uri = "verified"
media_get_stream_uri = "verified"
media_get_video_encoder_configurations = "verified"
media_get_video_source_configurations = "verified"
media_get_video_sources = "verified"
ptz_absolute_move = "verified"
ptz_absolute_move_malformed_coord = "verified"
ptz_continuous_move = "verified"
ptz_get_configuration_options = "verified"
ptz_get_configurations = "verified"
ptz_get_nodes = "verified"
ptz_get_status = "verified"
ptz_relative_move = "verified"
ptz_stop = "verified"
